spring:
  application:
    name: market-service

  mvc:
    throw-exception-if-no-handler-found: true


server:
  port: ${PORT:0}
  error:
    whitelabel:
      enabled: false
    include-exception: true
    path: ""

security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}