version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: cloud-bank-rabbit
    ports:
      - 5672:5672

  postgres:
    build: ./postgres
    container_name: cloud-bank-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  mongo:
    image: mongo:4.4.0
    container_name: cloud-bank-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=bank-transactions
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=password