spring:
  application:
    name: transactional-service

  data:
    mongodb:
      host: ${databases.transactions.host}
      port: ${databases.transactions.port}
      authentication-database: ${databases.transactions.authentication-database}
      database: ${databases.transactions.database}
      username: ${databases.transactions.username}
      password: ${databases.transactions.password}

    web:
      pageable:
        max-page-size: 20

  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: ${PORT:0}
  error:
    whitelabel:
      enabled: false
    include-exception: true
    path: ""

security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}