spring:
  application:
    name: transactional-service

  data:
    mongodb:
      host: ${databases.transactions.host}
      port: ${databases.transactions.port}
      authentication-database: ${databases.transactions.authentication-database}
      database: ${databases.transactions.database}
      username: ${databases.transactions.username}
      password: ${databases.transactions.password}

server:
  port: ${PORT:0}

security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}