oauth2:
  clients:
    - id: web
      secret: "{noop}password"
      redirectUri: "http://localhost:8080/login"
      authorizedGrantTypes:
        - authorization_code
        - refresh_token
      scopes: user_info
      autoApprove: true
      accessTokenValiditySeconds: 3600
      refreshTokenValiditySeconds: 86400