spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

application:
  classes: "5-а, 5-б, 6, 7, 8, 9, 10, 11"
  cards:
    default:
      name: "Classic"
      price: 0
      ableToBuy: true
      clientLimit: 1
      tax:
        award: 5.0
        fine: 5.0
        translate: 5.0
        salary: 5.0
        other: 5.0
    gold:
      name: "Gold"
      price: 100
      ableToBuy: true
      service: 10.0
      tax:
        award: 0.0
        fine: 0.0
        translate: 0.0
        salary: 0.0
        other: 0.0

databases:
  users:
    url: jdbc:postgresql://localhost:5432/bank-users
    username: postgres
    password: password
    initialization-mode: always
  market:
    url: jdbc:postgresql://localhost:5432/bank-market
    username: postgres
    password: password
    initialization-mode: always
  transactions:
    host: localhost
    port: 27017
    authentication-database: admin
    database: bank-transactions
    username: mongodb
    password: password

cron:
  # at 10:00 each first day of month
  salaryPayout: 0 0 10 1 * *
  # at 10:30 each first day of month
  cardPayouterJob: 0 30 10 1 * *

jwt:
  keyValue: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkS82g+/yvGzR9i0DwUlp
    FYiyZE6EsBKIL9UnQHkBfRva4xvDjfSdFbG1rEf337NAFnzUjPYrfHTtvZ6Zf7k/
    8ZhMyiJnL153rXPM66caO7cSAafin2w67CsC61Gl7unOsYlGi8wxah5G3m2LPvcJ
    Nw7xD9lp/NmPZuSbmMAeFYVUt2EkSZwyF5P6OIVBWXYB9X/54Vp5C6x7UyI2gQJn
    59lRPbnYkK92iV7KFefh5cjK5jxmHksm+06Nt6iew7QmLJRzRvnorw7kBylxueMd
    AGLA436592E/EpL+wI+bnXtyfYI4abhdOyy6VbVs5z0JeBL8wfHzKfE5XVq5dIfW
    mwIDAQAB
    -----END PUBLIC KEY-----

services:
  config-service:
    username: test
    password: test
  discovery-service:
    username: user
    password: pass

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${services.discovery-service.username}:${services.discovery-service.password}@localhost:8761/eureka"