server:
  port: 0
  error:
    whitelabel:
      enabled: false
    include-exception: true
    path: ""

spring:
  application:
    name: user-resource-service

  datasource:
    url: ${databases.users.url}
    username: ${databases.users.username}
    password: ${databases.users.password}
    driver-class-name: org.postgresql.Driver
    initialization-mode: never

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: validate

security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}