server:
  port: ${PORT:0}
  error:
    whitelabel:
      enabled: false
    include-exception: true
    path: ""

spring:
  application:
    name: user-resource-service

  datasource:
    url: ${databases.users.url}
    username: ${databases.users.username}
    password: ${databases.users.password}
    driver-class-name: org.postgresql.Driver
    initialization-mode: never

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: validate

  batch:
    initialize-schema: always
    # disabling job auto-launching, don't touch this
    job:
      enabled: false

  # will working only with profile 'salaryPayouter'
  scheduling:
    enabled: true

security:
  oauth2:
    resource:
      jwt:
        keyValue: ${jwt.keyValue}