name: Java Maven Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.0
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bank-users

      mongo:
        image: mongo:4.4.0
        ports:
          - 27017:27017
        environment:
          - MONGO_INITDB_DATABASE=bank-transactions
          - MONGO_INITDB_ROOT_USERNAME=mongodb
          - MONGO_INITDB_ROOT_PASSWORD=password

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn install --file pom.xml